name: 'Test Coverage Change'
description: 'Check test coverage change of changed files'
branding:
  icon: 'bar-chart'  
  color: 'green'
inputs:
  minNewCoverage:  # minimum new coverage
    description: 'minimum coverage a new file has to have to pass'
    default: 0.8
  maxCoverageChange: 
    description: 'Max amount coverage can reduce and pass'
    default: 0.5
  token:
    description: GitHub Personal Access Token
    required:    true
runs:
  using: 'node12'
  main: 'index.js'
