name: 'Test Coverage Change'
description: 'Check test coverage change of changed files'
icon: bar-chart
inputs:
  minNewCoverage:  # minimum new coverage
    description: 'minimum coverage a new file has to have to pass'
    default: 0.8
  maxCoverageChange: 
    description: 'Max amount coverage can reduce and pass'
    default: 0.5
outputs:
  Coverage:
    description: 'Coverage of changed files'
runs:
  using: 'node12'
  main: 'dist/index.js'
