name: 'Test Coverage Change'
description: 'Check test coverage change of changed files'
branding:
  icon: 'bar-chart'  
  color: 'green'
inputs:
  minNewCoverage:  # minimum new coverage
    description: 'minimum coverage a new file has to have to pass'
    default: 0.8
  maxCoverageChange: 
    description: 'Max amount coverage can reduce and pass'
    default: 0.5
   token:
    description: >
      GitHub token used to create and remove comments. By default, this uses the
      repository token provided by GitHub Actions. You can customize the user by
      replacing this token with a user token which has write-access to your
      repository. Note that the token will be accessible to all repository
      collaborators.
    default: ${{ github.token }}
outputs:
  Coverage:
    description: 'Coverage of changed files'
runs:
  using: 'node12'
  main: 'index.js'
